version: '3.8'
services:
  zookeeper:
    image: bitnami/zookeeper
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes

  kafka:
    image: bitnami/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 109.163.197.164
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  main-service:
    image: kafka-spring-parser-main-service
    ports:
      - "4322:4322"
    depends_on:
      - kafka
    environment:
      SPRING_KAFKA_BOOTSTRAP-SERVERS: kafka:9092

  kolesa-parser:
    image: kafka-spring-parser-kolesa-microservice
    ports:
      - "1029:1029"
    depends_on:
      - kafka
    environment:
      SPRING_KAFKA_BOOTSTRAP-SERVERS: kafka:9092

  olx-parser:
    image: kafka-spring-parser-olx-microservice
    ports:
      - "1031:1031"
    depends_on:
      - kafka
    environment:
      SPRING_KAFKA_BOOTSTRAP-SERVERS: kafka:9092

  youtube-parser:
    image: kafka-spring-parser-youtube-microservice
    ports:
      - "1030:1030"
    depends_on:
      - kafka
    environment:
      SPRING_KAFKA_BOOTSTRAP-SERVERS: kafka:9092
