server:
  port: 1031
spring:
  kafka:
    bootstrap-servers: kafka-container:9092
  datasource:
    url: jdbc:postgresql://192.168.1.121:5432/shopmanager
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver