FROM ubuntu:22.04

# Обновляем пакеты и устанавливаем необходимые инструменты
RUN apt-get update && apt-get install -y wget gnupg curl unzip openjdk-17-jdk maven

# Устанавливаем Chrome
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list \
    && apt-get update && apt-get -y install google-chrome-stable

# Устанавливаем совместимый ChromeDriver
RUN CHROME_DRIVER_VERSION=$(wget -q -O - https://chromedriver.storage.googleapis.com/LATEST_RELEASE) \
    && wget -q -O /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip \
    && unzip /tmp/chromedriver.zip -d /usr/bin \
    && rm /tmp/chromedriver.zip \
    && chmod +x /usr/bin/chromedriver

# Копируем и собираем приложение
WORKDIR /app
COPY . .
RUN mvn clean package

# Запускаем приложение
CMD ["java", "-jar", "target/parser-0.0.1-SNAPSHOT.jar"]
